name: Dispatched
on:
  push:
    tags:
      - '*'
    paths:
      - ".github/workflows/on-dispatch.yml"
  watch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT: ${{ toJson(github.event) }}
        run: echo $EVENT
