name: Dispatched
on:
  push:
    paths:
      - ".github/workflows/on-dispatch.yml"
  workflow_call:
    inputs:
      package_name:
        description: 'eg "astralweb/module-config-banner", must be same as defined in satis.json.'
        required: true
        type: string
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT: ${{ toJson(github.event) }}
        run: echo $EVENT
  # dispatch:
  #   runs-on: ubuntu-latest
  #   permissions: "write-all"
  #   steps:
  #     - env:
  #         ACCEPT_HEADER: "Accept: application/vnd.github+json"
  #         AUTH_HEADER: "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
  #         JSON_CONTENT: '{"event_type":"dispatch","client_payload":{"package_name": "${{ vars.PACKAGE_NAME }}"}}'
  #       run: curl -L -X POST -H "$ACCEPT_HEADER" -H "$AUTH_HEADER" https://api.github.com/repos/alexxss/satis-github/dispatches -d "$JSON_CONTENT"
  trigger:
    runs-on: ubuntu-latest
    permissions: "write-all"
    steps:
      - env:
          API: "https://api.github.com/repos/alexxss/satis-github/actions/workflows/deploy.yml/dispatches"
          JSON_CONTENT: '{"ref":"main", "inputs":{"package_name": "${{ inputs.package_name }}"}}'
        run: |
          curl -L -X POST -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $API -d "$JSON_CONTENT"
