name: Dispatched
on:
  workflow_call:
    inputs:
      package_name:
        description: 'eg "astralweb/module-config-banner", must be same as defined in satis.json.'
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'alexxss',
              repo: 'satis-github',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                package_name: '${{ vars.package_name }}',
              },
            })
