name: Dispatched
on:
  push:
    paths:
      - ".github/workflows/on-dispatch.yml"
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT: ${{ toJson(github.event) }}
        run: echo $EVENT
      - run: echo ${{ secrets.GITHUB_TOKEN }}
